version = 0.1
[default.deploy.parameters]
stack_name = "taratasy"
resolve_s3 = true
s3_prefix = "taratasy"
region = "eu-central-1"
profile = "bp"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "IzaUri=\"https://iza-mock.hei.school\" IzaApiKey=\"iza-mock-server-api-key\""
image_repositories = []
