AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Yet another file API, in REST.

Parameters:
  IzaUri:
    Type: String
  IzaApiKey:
    Type: String

Globals:
  Function:
    CodeUri: functions
    Runtime: java17
    Tracing: Active
    Architectures:
      - x86_64
    Timeout: 15
    MemorySize: 512
    AutoPublishAlias: live
    SnapStart:
      ApplyOn: PublishedVersions
    Environment:
      Variables:
        TABLE_NAME: !Ref Table
        IZA_URI: !Ref IzaUri
        IZA_API_KEY: !Ref IzaApiKey

Resources:
  GetFilesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: taratasy.handler.GetFilesHandler::apply
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Table
      Events:
        GetFiles:
          Type: Api
          Properties:
            Path: /users/{userId}/files
            Method: get
  GetFileByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: taratasy.handler.GetFileByIdHandler::apply
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref Table
      Events:
        GetFileById:
          Type: Api
          Properties:
            Path: /users/{userId}/files/{fileId}
            Method: get
  DreactivateFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: taratasy.handler.DreactivateFileHandler::apply
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Table
      Events:
        DreactivateFile:
          Type: Api
          Properties:
            Path: /users/{userId}/files/{fileId}/status
            Method: put

  Table:
    Type: AWS::DynamoDB::Table
    Properties: 
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - AttributeName: ownerId
          AttributeType: S
        - AttributeName: fileId
          AttributeType: S
      KeySchema:
        - AttributeName: ownerId
          KeyType: HASH
        - AttributeName: fileId
          KeyType: RANGE

Outputs:
  Api:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com"
